# Generated by Django 2.0 on 2017-12-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_auto_20171229_1156'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmark',
            table=None,
        ),
    ]
