name: 'Tag Repository'
author: 'Tom Henderson'
description: 'Tag a github repository'
branding:
  icon: 'tag'
  color: 'gray-dark'

inputs:
  tag:
    description: 'Tag'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}

