# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('add_date', models.CharField(max_length=200)),
                ('tags', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
