# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookmark_tag_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
