# Generated by Django 2.0 on 2017-12-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160901_2322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmark',
            table='core_bookmark',
        ),
    ]
