# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_bookmark_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
    ]
