# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 08:25
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bookmark_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='add_date',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
