# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160829_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 29, 8, 29, 54, 116089, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
