name: Bookmarks

on:
  workflow_dispatch:

  schedule:
    - cron: '0 19 1 * *' # At 19:00 UTC on the 1st day of every month

  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/container-build.yml
    with:
      image-name: bookmarks
    secrets: inherit
