name: Tests

on:
  pull_request:
  workflow_call:

jobs:
  test:
    name: Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bookmarks-test .

      - name: Run Django tests
        run: docker run --rm -e DJANGO_SETTINGS_MODULE=config.settings.test bookmarks-test python /app/manage.py test bookmarks api --verbosity=2

